### PR TITLE
Support new setupHooks argument format for Node versions v5.10  or later

### PR DESCRIPTION
**Pull request by jgwmaxwell**
Happy to amend this however you want, but this keeps the test suite green and gets the library working with v5.10

### CODE REVIEW

**Comment by AndreasMadsen** [comment]
Thanks.

It turns out that maintaining backward compatibility with older versions of async wrap becomes a nightmare very quickly. Thus I have previously decided to not try at all, and just support the latest version.  

The supported version should be specified in the `package.json` file, https://github.com/AndreasMadsen/async-hook/blob/master/package.json#L29 in this case `^5.10`. That way other modules may detect the appropriate version (npm doesn't do that by default, but it is possible).

**Comment by jgwmaxwell** [comment]
Thanks for getting back so quickly! Cool - that makes it easier, and then locking to the current release for node 5.9 and below works nicely. If you're interested in this PR would you like me to do anything other than remove the check?

**Comment by AndreasMadsen** [comment]
Just, update the engine field and _drop_ 8769da6. Otherwise perfect!

**Comment by jgwmaxwell** [comment]
Updated as requested.

**Comment by jgwmaxwell** [comment]
Updated as requested.

**Comment by AndreasMadsen** [comment]
Landed in 951e7433ae92bf1b7ec40398dd77da823cc14213. I squahed and edited the commit message, I hope that is fine.

**Comment by jgwmaxwell** [comment]
Awesome - thanks so much for a quick turnaround!

**Pull request closed without merging**
